### ISSUE TITLE
Offset seems to be wrong for some chars

### ISSUE THREAD

**Issue by agalakhov** [sbechet/ibm437#6]
Hi,

Test case: print "Hello World!" as in the embedded-graphics example.
Text as observed on the screen: "Hello/World "

**Comment by sbechet** [comment]
Hello Agalakhov,

Can you test the characters exhaustively so that we can definitively correct this problem?

You can print all characters using `data/Characters.txt`.

Maybe @bugadani can help.

Thank you.

**Comment by bugadani** [comment]
Hmm, thanks for letting me know, it's possible that this is my fault. Can you check if the old version works for you?
